### ISSUE TITLE
Can pyswf generate SWF files from scratch?

### ISSUE THREAD

**Issue by otherthings** [timknip/pyswf#20]
I'm trying to convert some SVG files to SWF for an old web project I'm restoring (http://grafarc.org/flash/view.htm). The files themselves are very basic, just static vector outlines made mostly of straight-edged shapes.

Is pyswf capable of generating an SWF from scratch, or can it only read them from existing files?  I can't quite tell from the documentation.

-Cassidy

**Comment by timknip** [comment]
No, at the moment pyswf only "reads" swf.
I should update the readme to reflect this.

Simply don't have the time to implement "write".
