### ISSUE TITLE
does pyswf support open .swf file with a remote url?

### ISSUE THREAD

**Issue by albertyou2** [timknip/pyswf#46]
Hi @timknip 
Thanks for your work !

My problem is to open a swf steam from a  http server. i got the swf  file url like 'http://xxxxx/swf'
Does pyswf support open and read swf  stream from a http server?

thankyou

**Comment by timknip** [comment]
I guess not ;-)
(its been a while since i checked pyswf code)

Just use urllib or whatever to pull the swf from url and run pyswf on it.

T

2017-02-27 10:37 GMT+01:00 albertyou2 <notifications@github.com>:

**Comment by albertyou2** [comment]
@timknip 
oK ,thank you !
